name: Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "riemannax/**"
      - "tests/**"
      - "pyproject.toml"
  push:
    branches: [main]
    paths:
      - "riemannax/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  test-py310:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]" || pip install -e .
          pip install pytest-cov pytest-xdist pytest-timeout matplotlib seaborn pandas scikit-learn
      - name: Run tests
        run: |
          pytest --cov=riemannax --timeout=900 --maxfail=10 -v --tb=short
        env:
          JAX_PLATFORMS: cpu
          XLA_PYTHON_CLIENT_PREALLOCATE: false
          JAX_ENABLE_X64: true
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: ${{ github.repository_owner == 'username' }}
        with:
          file: .coverage
          fail_ci_if_error: false
  test-py311:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]" || pip install -e .
          pip install pytest-cov pytest-xdist pytest-timeout matplotlib seaborn pandas scikit-learn
      - name: Run tests
        run: |
          pytest --cov=riemannax --timeout=900 --maxfail=10 -v --tb=short
        env:
          JAX_PLATFORMS: cpu
          XLA_PYTHON_CLIENT_PREALLOCATE: false
          JAX_ENABLE_X64: true
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: ${{ github.repository_owner == 'username' }}
        with:
          file: .coverage
          fail_ci_if_error: false
  test-py312:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]" || pip install -e .
          pip install pytest-cov pytest-xdist pytest-timeout matplotlib seaborn pandas scikit-learn
      - name: Run tests
        run: |
          pytest --cov=riemannax --timeout=900 --maxfail=10 -v --tb=short
        env:
          JAX_PLATFORMS: cpu
          XLA_PYTHON_CLIENT_PREALLOCATE: false
          JAX_ENABLE_X64: true
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: ${{ github.repository_owner == 'username' }}
        with:
          file: .coverage
          fail_ci_if_error: false
